### ISSUE TITLE
部分Android机型上出现：attempt to write a readonly database 

### ISSUE THREAD

**Issue by afayp** [Tencent/wcdb#101]
少部分Android机型上出现上述问题，切换为sqlite后就正常了，不知是否要有其他特殊设置？

**Comment by John-He-928** [comment]
请提供log和具体代码

**Comment by Heycz** [comment]
用了ormlite和wcdb,把https://github.com/Andoctorey/ormlite-sqlcipher 改到wcdb,然后开启事务调用dao的delete就报错了,原来没问题的
`                                                                      Caused by: com.tencent.wcdb.database.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032, errno 0): 
                                                                         at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                         at com.tencent.wcdb.database.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:780)
                                                                         at com.tencent.wcdb.database.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:706)
                                                                         at com.tencent.wcdb.database.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:62)
                                                                         at com.tencent.wcdb.database.SQLiteDatabase.executeSql(SQLiteDatabase.java:1883)
                                                                         at com.tencent.wcdb.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:1862)`

**Comment by Heycz** [comment]
华为P9上报这个错,但是在锤子T1没有报错

**Comment by John-He-928** [comment]
你们看一下SQLiteOpenHelper，有个逻辑是没法用读写打开就用只读打开，可否单步一下看看是不是这里问题用只读打开了？

**Comment by Heycz** [comment]
@John-He-928 P9突然好了没有重现了..

**Comment by afayp** [comment]
@John-He-928 只是在部分用户上发现这个错误（比例很小），目前也没有重现。但是为何会没法打开writable的数据库呢？

**Comment by John-He-928** [comment]
@afayp 应该跟具体用户环境或机型相关，如果能收集到logcat，可能可以看下

**Comment by HiWong** [comment]
这个是由于SQLite的hot_journal导致的，详情如下:https://stackoverflow.com/questions/30082008/attempt-to-write-a-readonly-database-but-im-not
