### ISSUE TITLE
Crash! Please support 16kb page size on Android 15!

### ISSUE THREAD

**Issue by ysy950803** [Tencent/wcdb#1179]
### The language of WCDB

Java

### The version of WCDB

v1.1-19

### The platform of WCDB

Android

### The installation of WCDB

AAR Package

### What's the issue?

```
---------------------------- PROCESS STARTED (27211) for package com.xxx.xxx ----------------------------
2024-09-05 17:16:24.227 27211-27211 AndroidRuntime          com.xxx.xxx                  E  FATAL EXCEPTION: main
                                                                                            Process: com.xxx.xxx, PID: 27211
                                                                                            java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~QvGPE8ss-owpYxC1bQsPvw==/com.xxx.xxx-43qqbRIQ77WhHAyx2TTqzw==/base.apk!/lib/x86_64/libwcdb.so" (new hash type from the future?)
                                                                                            	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
                                                                                            	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                            	at java.lang.System.loadLibrary(System.java:1765)
                                                                                            	at com.tencent.wcdb.database.SQLiteGlobal.<clinit>(SQLiteGlobal.java:66)
                                                                                            	at com.tencent.wcdb.database.SQLiteOpenHelper.<clinit>(SQLiteOpenHelper.java:49)
```

https://developer.android.com/guide/practices/page-sizes?hl=zh-cn#update-packaging

**Comment by ysy950803** [comment]
Please recompile `so` for Android.

**Comment by Qiuwen-chen** [comment]
Please try the latest version. I don't have time to support the old versions.

**Comment by ysy950803** [comment]
[Support 16KB page size for WCDB 1.x](https://github.com/ysy950803/wcdb/commit/b00eda95e1ac6845dff6770de04dafde5508512b)
