### ISSUE TITLE
disk I/O error (code 4874, errno 28): , while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1261]
### The language of WCDB

> Java

### The version of WCDB

> 1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

any suggestion about the error "disk I/O error (code 4874, errno 28)"

```
at com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 4874, errno 28): , while compiling: PRAGMA journal_mode
at com.tencent.wcdb.database.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
at com.tencent.wcdb.database.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:996)
at com.tencent.wcdb.database.SQLiteConnection.executeForString(SQLiteConnection.java:775)
at com.tencent.wcdb.database.SQLiteConnection.setJournalMode(SQLiteConnection.java:393)
at com.tencent.wcdb.database.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:383)
at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:273)
at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:238)
at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:502)
at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:216)
at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:997)
at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:978)
at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:151)
at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)
at com.tencent.wcdb.room.db.WCDBOpenHelper$OpenHelper.getWritableSupportDatabase(WCDBOpenHelper.java:99)
at com.tencent.wcdb.room.db.WCDBOpenHelper.getWritableDatabase(WCDBOpenHelper.java:48)
```
issue https://github.com/Tencent/wcdb/issues/456

**Comment by Qiuwen-chen** [comment]
errno 28 means no space left on disk.
