### ISSUE TITLE
安卓项目经常出现此错误

### ISSUE THREAD

**Issue by lihywh** [Tencent/wcdb#136]
请问此报错是什么含义？
com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 1802, errno 4): 
	at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at com.tencent.wcdb.database.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:881)
	at com.tencent.wcdb.database.SQLiteSession.executeForCursorWindow(SQLiteSession.java:786)
	at com.tencent.wcdb.database.SQLiteQuery.fillWindow(SQLiteQuery.java:63)
	at com.tencent.wcdb.database.SQLiteCursor.fillWindow(SQLiteCursor.java:146)
	at com.tencent.wcdb.database.SQLiteCursor.getCount(SQLiteCursor.java:135)
	at com.tencent.wcdb.AbstractCursor.moveToPosition(AbstractCursor.java:200)
	at com.tencent.wcdb.AbstractCursor.moveToFirst(AbstractCursor.java:240)
	at com.mao.openapirobot.data.DebtDbHelper.isContain(DebtDbHelper.java:199)

**Comment by John-He-928** [comment]
fstat调用失败，错误码是EINTR，我们这边暂时没遇到，是否和手机有关
