### ISSUE TITLE
更新到最新的安卓版本大量出现如下错误

### ISSUE THREAD

**Issue by lihywh** [Tencent/wcdb#157]
上个版本也有出现，但是概率很低，最新版本概率非常高。

java.util.concurrent.ExecutionException: com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 1034, errno 4): 
	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
	at com.mao.openapirobot.repayment.RepaymentService.scheduleRefreshingRepay(RepaymentService.java:265)
	at com.mao.openapirobot.repayment.RepaymentService.access$0(RepaymentService.java:258)
	at com.mao.openapirobot.repayment.RepaymentService$1.handleMessage(RepaymentService.java:171)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5645)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 1034, errno 4): 
	at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at com.tencent.wcdb.database.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:804)
	at com.tencent.wcdb.database.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:708)
	at com.tencent.wcdb.database.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:91)
	at com.tencent.wcdb.database.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:75)
	at com.tencent.wcdb.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1790)
	at com.tencent.wcdb.database.SQLiteDatabase.update(SQLiteDatabase.java:1736)
	at com.mao.openapirobot.repayment.RepayDbHelper.updateFetchedData(RepayDbHelper.java:146)
	at com.mao.openapirobot.repayment.RepayDBManager.updateFetchedData(RepayDBManager.java:47)
	at com.mao.openapirobot.repayment.RepaymentCallable.call(RepaymentCallable.java:120)
	at com.mao.openapirobot.repayment.RepaymentCallable.call(RepaymentCallable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 1034, errno 4): 
	at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at com.tencent.wcdb.database.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:804)
	at com.tencent.wcdb.database.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:708)
	at com.tencent.wcdb.database.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:91)
	at com.tencent.wcdb.database.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:75)
	at com.tencent.wcdb.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1790)
	at com.tencent.wcdb.database.SQLiteDatabase.update(SQLiteDatabase.java:1736)
	at com.mao.openapirobot.repayment.RepayDbHelper.updateFetchedData(RepayDbHelper.java:146)
	at com.mao.openapirobot.repayment.RepayDBManager.updateFetchedData(RepayDBManager.java:47)
	at com.mao.openapirobot.repayment.RepaymentCallable.call(RepaymentCallable.java:120)
	at com.mao.openapirobot.repayment.RepaymentCallable.call(RepaymentCallable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by John-He-928** [comment]
看日志是fsync时错误，errno是EINTR。是fsync时错误但没有重试，是底层SQLite的问题。这部分应该没有改，不是很懂为什么会爆发。

这边尝试修正一下SQLite底层
