### ISSUE TITLE
room分支wal模式不支持并发

### ISSUE THREAD

**Issue by lightai** [Tencent/wcdb#163]
https://github.com/Tencent/wcdb/blob/room/android/wcdb/src/com/tencent/wcdb/database/SQLiteOpenHelper.java#L205

git提交日志是：
Room: force connection pool size to 1.  It seems Room is not compatible with connection pooling on the moment.

具体原因是什么呢？如果不支持并发开启wal就没有意义了

**Comment by lightai** [comment]
连接池强制限制只能开启一个连接的话，就不能并发读写sqlite，那么开启wal也不能并发读写sqlite了，麻烦你们处理一下这个问题！

**Comment by John-He-928** [comment]
这个问题比较麻烦，因为Room的实现使用了TEMP TABLE，不能在链接之间共享，我们已经向Google提了issue，看他们会不会跟进。

现在Google还没正式开源Room，所以暂时不能改这个问题，我们会持续跟进，如果Google最后没改这个问题，我们会fork一个来修正这个问题。

**Comment by lightai** [comment]
赞啊！
不过room那边优先级才P3，汗...
我把链接贴出来大家一起围观[](https://issuetracker.google.com/issues/67757002)

**Comment by guixb** [comment]
ROOM开ROOM会crash，打不开DB~~在官网上找不到反馈的入口，请问下反馈的话一般通过邮件吗

**Comment by lightai** [comment]
@guixb 你是Use LiveData with Room吧，room代码上看room wal并发跟LiveData一起用会crash，不用live data开启room wal应该没有问题

**Comment by donglua** [comment]
会 crash 的，跟 live data 没有关系。

**Comment by donglua** [comment]
报这个错~

```
com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 5386, errno 22): , while compiling: PRAGMA journal_mode
at com.tencent.wcdb.database.SQLiteConnection.nativePrepareStatement(Native Method)
at com.tencent.wcdb.database.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:962)
at com.tencent.wcdb.database.SQLiteConnection.executeForString(SQLiteConnection.java:741)
at com.tencent.wcdb.database.SQLiteConnection.setJournalMode(SQLiteConnection.java:386)
at com.tencent.wcdb.database.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:376)
at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:267)
at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:233)
at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:497)
at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:211)
at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:203)
at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:1009)
at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:990)
at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:722)
at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:150)
at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)
at com.tencent.wcdb.room.db.WCDBOpenHelper$OpenHelper.getWritableSupportDatabase(WCDBOpenHelper.java:95)
at com.tencent.wcdb.room.db.WCDBOpenHelper.getWritableDatabase(WCDBOpenHelper.java:54)
at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
```

**Comment by crossle** [comment]
那只能暂时开两个 Database connection 来解决一下了

**Comment by lightai** [comment]
@crossle，room分支已经可以wal开启连接池了，这个issue可以关闭了。
