### ISSUE TITLE
SQLiteDatabaseCorruptException file is encrypted or is not a database while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by andyken** [Tencent/wcdb#207]
Fatal Exception: com.tencent.wcdb.database.SQLiteDatabaseCorruptException: file is encrypted or is not a database (code 26, errno 0): , while compiling: PRAGMA journal_mode
       at com.tencent.wcdb.database.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at com.tencent.wcdb.database.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:962)
       at com.tencent.wcdb.database.SQLiteConnection.executeForString(SQLiteConnection.java:741)
       at com.tencent.wcdb.database.SQLiteConnection.setJournalMode(SQLiteConnection.java:386)
       at com.tencent.wcdb.database.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:376)
       at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:267)
       at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:233)
       at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:497)
       at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:211)
       at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:203)
       at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:1009)
       at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:997)
       at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:722)
       at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:150)
       at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
       at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)
       at com.tencent.wcdb.room.db.WCDBOpenHelper$OpenHelper.getWritableSupportDatabase(WCDBOpenHelper.java:95)
       at com.tencent.wcdb.room.db.WCDBOpenHelper.getWritableDatabase(WCDBOpenHelper.java:54)
       at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)

**Comment by John-He-928** [comment]
请问复现场景和详细log

**Comment by MichaelNing** [comment]
<img width="1052" alt="1" src="https://user-images.githubusercontent.com/5234517/38464788-1d12eb60-3b46-11e8-9a88-f72b045436e6.png">
<img width="1046" alt="2" src="https://user-images.githubusercontent.com/5234517/38464789-1e38cd84-3b46-11e8-9ffd-ecbbb5d1ded9.png">
<img width="1049" alt="3" src="https://user-images.githubusercontent.com/5234517/38464790-1f7316be-3b46-11e8-87f2-434f421c9c58.png">
<img width="897" alt="4" src="https://user-images.githubusercontent.com/5234517/38464791-20cd2248-3b46-11e8-989f-4378f1fe07c0.png">

同样的问题～

**Comment by MichaelNing** [comment]
@John-He-928 请问有回复吗？

**Comment by liu12151407** [comment]
请问有知道出现这个问题的原因麽？我这边几部手机（品牌型号一样），其中代码一模一样，但是其中2两部就一直报 `file is encrypted or is not a database (code 26, errno 0): , while compiling: PRAGMA journal_mode` 这个问题...

**Comment by xiaodongyang-prog** [comment]
我也出现这种问题了，按照其他问题里面的方法试过，没有用。目前只有两台手机出现，其他运行正常， 莫名其妙啊....
