### ISSUE TITLE
attach database and copy some column to new database

### ISSUE THREAD

**Issue by iamcxl369** [Tencent/wcdb#330]
v1.0.5

Android
### What's the issue?

usage：
```
        //这个是将要创建的新的数据库，需要把老的数据库(encrypt_db.db)中的两个字段copy过来。
        String to = ctxt.getDatabasePath(DBHelper.DB_NAME_OLD).getParent()+"/cpy_colum.db";

        //这个是老的数据库，需要把这个库中的某个表的两个字段copy到新的数据库中
        String from =  originalFile.getParentFile().getPath()+ File.separator + "encrypt_db.db";
        copyColum2NewDatabase(ctxt, "xxxxxx", from, to);
```
implements：
```
    public static void copyColum2NewDatabase(Context context, String passphrase, String from, String to){
        Log.i(TAG, "copyColum2NewDatabase()  ------>");

        Log.i(TAG, "copyColum2NewDatabase()  from:"+from);
        Log.i(TAG, "copyColum2NewDatabase()  to:"+to);
        if (!TextUtils.isEmpty(from)){
            File old = new File(from);
            if (old.exists()){
                SQLiteDatabase db = SQLiteDatabase.openOrCreateDatabase(
                        to.toString(),
                        passphrase.getBytes(),
                        null,
                        null);

                db.execSQL(String.format("ATTACH DATABASE '%s' AS encrypted KEY '%s';", from, "xxxxxx".getBytes()/*passphrase.getBytes()*/));
//                DatabaseUtils.stringForQuery(db, "SELECT sqlcipher_export('main', 'encrypted');", null);
                String result0 = DatabaseUtils.stringForQuery(db, "CREATE TABLE user2(user_pin,host); ", null);
                String result1 = DatabaseUtils.stringForQuery(db, "insert into user2 select (user_pin,host) from encrypt_db._USER_; ", null);
                String result2 = DatabaseUtils.stringForQuery(db, "select * from user2; ", null);
                db.execSQL("DETACH DATABASE decrypted;");

                db.close();

                Log.i(TAG, "copyColum2NewDatabase()  result0:"+result0);
                Log.i(TAG, "copyColum2NewDatabase()  result1:"+result1);
            }
        }
        Log.i(TAG, "copyColum2NewDatabase()  <------");
    }
```
error log：
```
07-17 20:37:40.885 637-637/com.iamcxl.database I/CryptUtils: copyColum2NewDatabase()  ------>
    copyColum2NewDatabase()  from:/data/data/com.iamcxl.database/databases/encrypt_db.db
    copyColum2NewDatabase()  to:/data/data/com.iamcxl.database/databases/cpy_colum.db
07-17 20:37:40.885 637-637/com.iamcxl.database I/WCDB.SQLiteConnectionPool: Max connection pool size is 1.
07-17 20:37:40.890 637-637/com.iamcxl.database I/WCDB: Initialize SQLite connection module 'MMFTS'...
07-17 20:37:40.890 637-637/com.iamcxl.database I/WCDB.SQLiteConnection: Opened connection 0x7a1b9d08 with label '/data/data/com.iamcxl.database/databases/cpy_colum.db'
    sqlite3_key verification passed.
07-17 20:37:41.285 637-637/com.iamcxl.database W/WCDB.SQLite: [SQLite ErrCode: 26] statement aborts at 4: [ATTACH DATABASE '/data/data/com.iamcxl.database/databases/encrypt_db.db' AS encrypted KEY '[B@43840c20';] file is encrypted or is not a database
07-17 20:37:41.285 637-637/com.iamcxl.database I/WCDB.SQLiteConnection: executeForChangedRowCount took 395ms - failed, sql="ATTACH DATABASE '/data/data/com.iamcxl.database/databases/encrypt_db.db' AS encrypted KEY '[B@43840c20';", tid=637, exception="file is encrypted or is not a database (code 26, errno 0): ", changedRows=0
07-17 20:37:41.285 637-637/com.iamcxl.database E/WCDB.DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/data/com.iamcxl.database/databases/cpy_colum.db
    Remove database file: /data/data/com.iamcxl.database/databases/cpy_colum.db
07-17 20:37:41.290 637-637/com.iamcxl.database E/WCDB.DefaultDatabaseErrorHandler: Could not create directory for corrupted database. Corruption backup may be unavailable.
07-17 20:37:41.290 637-637/com.iamcxl.database V/WCDB.SQLiteConnection: Closing connection 0x7a1b9d08
07-17 20:37:41.290 637-637/com.iamcxl.database W/WCDB.SQLite: [SQLite ErrCode: 28] file renamed while open: /data/data/com.iamcxl.database/databases/cpy_colum.db
07-17 20:37:41.290 637-637/com.iamcxl.database D/AndroidRuntime: Shutting down VM
07-17 20:37:41.290 637-637/com.iamcxl.database W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4160fc50)
07-17 20:37:41.310 637-637/com.iamcxl.database D/dalvikvm: JIT code cache reset in 0 ms (4096 bytes 3/0)
    GC_FOR_ALLOC freed 1844K, 9% free 32297K/35116K, paused 20ms, total 20ms
07-17 20:37:41.310 637-637/com.iamcxl.database E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iamcxl.database, PID: 637
    com.tencent.wcdb.database.SQLiteDatabaseCorruptException: file is encrypted or is not a database (code 26, errno 0): 
        at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at com.tencent.wcdb.database.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:800)
        at com.tencent.wcdb.database.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:709)
        at com.tencent.wcdb.database.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:91)
        at com.tencent.wcdb.database.SQLiteDatabase.executeSql(SQLiteDatabase.java:1920)
        at com.tencent.wcdb.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:1824)
        at com.iamcxl.database.wcdb.CryptUtils.copyColum2NewDatabase(CryptUtils.java:307)
        at com.iamcxl.database.wcdb.CryptUtils.encrypt(CryptUtils.java:174)
        at com.iamcxl.database.DataBaseActivity$2.onClick(DataBaseActivity.java:64)
        at android.view.View.performClick(View.java:4446)
        at android.view.View$PerformClick.run(View.java:18480)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
        at dalvik.system.NativeStart.main(Native Method)
07-17 20:37:41.360 637-715/com.iamcxl.database E/TAG: ----------------------------------
```

**Comment by iamcxl369** [comment]
@RingoD 劳烦给点建议？感谢

**Comment by RingoD** [comment]
@John-He-928
