### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by nickyangjun** [Tencent/wcdb#355]
### Android数据库损坏

>使用wcdb版本： v1.0.5

我们App用户有比较频繁的数据库操作，偶尔会出现下面报错日志，导致数据库信息丢失，不知道如何解决。求解法。
```
 com.tencent.wcdb.database.SQLiteDatabaseCorruptException: database disk image is malformed (code 11, errno 0): 
at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at com.tencent.wcdb.database.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:901)
at com.tencent.wcdb.database.SQLiteSession.executeForCursorWindow(SQLiteSession.java:789)
at com.tencent.wcdb.database.SQLiteQuery.fillWindow(SQLiteQuery.java:63)
at com.tencent.wcdb.database.SQLiteCursor.fillWindow(SQLiteCursor.java:146)
at com.tencent.wcdb.database.SQLiteCursor.getCount(SQLiteCursor.java:135)
at com.tencent.wcdb.AbstractCursor.moveToPosition(AbstractCursor.java:200)
at com.tencent.wcdb.AbstractCursor.moveToNext(AbstractCursor.java:248)
at com.sgm.d.h.g(WCDBOperation.java:548)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by RingoD** [comment]
The wiki of Repair kit for corrupted database is already described in wiki.

**Comment by nickyangjun** [comment]
我导出已损坏的数据库用RepairKit去修复，是无法找回丢失的数据的。难道RepairKit只能在数据库还处于正常情况下时备份了MasterInfo的情况下，才能恢复其数据？

**Comment by RingoD** [comment]
Yes and it's already described in the wiki.
