### ISSUE TITLE
I met ANR using wcdb

### ISSUE THREAD

**Issue by wangduanqing5945** [Tencent/wcdb#434]
### The language of WCDB

> Java 

### The platform of WCDB

> v1.0.6.2

### The installation of WCDB

> Git clone

### What's the issue?

> 
> 
> "main" prio=5 tid=1 TimedWaiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7364ca68 self=0xeb78f000
  | sysTid=13135 nice=-10 cgrp=default sched=0/0 handle=0xef5a34a4
  | state=S schedstat=( 1600460107 182499428 1856 ) utm=138 stm=22 core=7 HZ=100
  | stack=0xff38f000-0xff391000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x07aa160b> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2137)
  - locked <0x07aa160b> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:353)
  at com.tencent.wcdb.database.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:710)
  at com.tencent.wcdb.database.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:375)
  at com.tencent.wcdb.database.SQLiteSession.acquireConnection(SQLiteSession.java:857)
  at com.tencent.wcdb.database.SQLiteSession.prepare(SQLiteSession.java:580)
  at com.tencent.wcdb.database.SQLiteProgram.<init>(SQLiteProgram.java:63)
  at com.tencent.wcdb.database.SQLiteQuery.<init>(SQLiteQuery.java:38)
  at com.tencent.wcdb.database.SQLiteCursor$1.newQuery(SQLiteCursor.java:283)
  at com.tencent.wcdb.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:53)
  at com.tencent.wcdb.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1503)
  at com.tencent.wcdb.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1442)
  at com.immomo.momo.service.d.b.query(BaseDao.java:188)
  at com.immomo.momo.service.d.b.list(BaseDao.java:266)
  at com.immomo.momo.k.c.a.a(DiscussMsgService.java:485)
  at com.immomo.momo.message.activity.MultiChatActivity.F(MultiChatActivity.java:919)
  at com.immomo.momo.mvp.message.view.BaseMessageActivity.ay(BaseMessageActivity.java:2876)
  at com.immomo.momo.message.a.a.ac.onClick(ImageMessageItem.java:198)
  at android.view.View.performClick(View.java:6391)
  at android.view.View$PerformClick.run(View.java:25144)
  at android.os.Handler.handleCallback(Handler.java:790)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:200)
  at android.app.ActivityThread.main(ActivityThread.java:7038)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**Comment by wangduanqing5945** [comment]
I found "com.tencent.wcdb.database.SQLiteConnectionPool#CONNECTION_POOL_BUSY_MILLIS" 3000 VS "android.database.sqlite.SQLiteConnectionPool#CONNECTION_POOL_BUSY_MILLIS" = 30 * 1000。why

**Comment by yangjiantao** [comment]
i meet same issue.

**Comment by John-He-928** [comment]
Connection pool busy waiting is probably because you used a connection and did not release it back to the connection pool. Common case is **opening a transaction by `beginTransaction` but no releasing by `endTransaction`**. This can happen while you are writing to DB in WAL mode, or reading/writing in legacy mode. (That is, not calling `enableWritaheadLogging` or so).

You may check your situation by calling `SQLiteDatabase.dump` to dump status of all connections in the connection pool to find out which connection is not released. You can set a trace callback to the DB and implement `onConnectionPoolBusy` method, in which you `dump` the database to print info about the connections.

The master branch contains code to print active transactions in `dump` to help debugging transaction dead-locks. It's not in release versions yet. If you need this info, build master branch yourself.
