### ISSUE TITLE
disk I/O error (code 4874, errno 28): , while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by lkasdolka** [Tencent/wcdb#456]
> The language of WCDB
> Java
> 
> The version of WCDB
>  v1.0.8
> 
> The version of room
> v1.1.1
> 
> The platform of WCDB
>  Android
> 
> The installation of WCDB
>  Maven

We use wcdb together with room database. Recently we found that our app crash occurred on some phones when we tried to initialized the sqlite db with wal mode. I found a similar issue: https://github.com/Tencent/wcdb/issues/243, the solution of that one is to close wal mode. But our app have lots of db operations, we think closing wal mode would extremely harm app's performance. So what would the reason causing this problem, and any solution suggested?

Below is the stacktrace we found on some android phones: 

```
at com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 4874, errno 28): , while compiling: PRAGMA journal_mode
at com.tencent.wcdb.database.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
at com.tencent.wcdb.database.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:996)
at com.tencent.wcdb.database.SQLiteConnection.executeForString(SQLiteConnection.java:775)
at com.tencent.wcdb.database.SQLiteConnection.setJournalMode(SQLiteConnection.java:393)
at com.tencent.wcdb.database.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:383)
at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:273)
at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:238)
at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:502)
at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:216)
at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:997)
at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:978)
at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:151)
at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)
at com.tencent.wcdb.room.db.WCDBOpenHelper$OpenHelper.getWritableSupportDatabase(WCDBOpenHelper.java:99)
at com.tencent.wcdb.room.db.WCDBOpenHelper.getWritableDatabase(WCDBOpenHelper.java:48)
at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:233)
at com.android.MyDataDao_Impl$6.compute(MyDataDao_Impl.java:402)
at com.android.MyDataDao_Impl$6.compute(MyDataDao_Impl.java:388)
at android.arch.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:100)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by tianxia--** [comment]
com.tencent.wcdb.database.SQLiteDiskIOException: disk I/O error (code 778, errno 9): 
        at com.tencent.wcdb.database.SQLiteConnection.nativeExecute(Native Method)
        at com.tencent.wcdb.database.SQLiteConnection.execute(SQLiteConnection.java:684)
        at com.tencent.wcdb.database.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:436)
        at com.tencent.wcdb.database.SQLiteSession.endTransaction(SQLiteSession.java:400)
        at com.tencent.wcdb.database.SQLiteDatabase.endTransaction(SQLiteDatabase.java:528)
        at com.tencent.wcdb.room.db.WCDBDatabase.endTransaction(WCDBDatabase.java:99)
        at com.blue.search.db.SearchTableDao.saveDataToDb(SearchTableDao.java:594)
        at com.blue.search.db.SearchTableDao.indexData(SearchTableDao.java:182)
        at com.blue.search.SearchSdkImpl.lambda$indexData$0$SearchSdkImpl(SearchSdkImpl.java:71)
        at com.blue.search.-$$Lambda$SearchSdkImpl$nGkFyzF76kNwQdzomc5TkhxURr8.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by sooglejay** [comment]
这个issue我们App线上遇到很多，有什么解决方案么？
