### ISSUE TITLE
crash in android Q(failed to load ICU library)

### ISSUE THREAD

**Issue by paulzengyi** [Tencent/wcdb#476]
### The language of WCDB
Java 

### The version of WCDB
com.tencent.wcdb:room:1.0.8

### The platform of WCDB
Android

### The installation of WCDB
gradle

### What's the issue?
crash in android Q
stack:
com.tencent.wcdb.database.SQLiteException: failed to load ICU library. (code 1, errno -1): Database connection initializer failed.
        at com.tencent.wcdb.database.SQLiteConnection.nativeOpen(Native Method)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:254)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:238)
        at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:502)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:216)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
        at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:997)
        at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:978)
        at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
        at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:151)
        at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
        at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)
        at com.tencent.wcdb.room.db.WCDBOpenHelper$OpenHelper.getWritableSupportDatabase(WCDBOpenHelper.java:101)
        at com.tencent.wcdb.room.db.WCDBOpenHelper.getWritableDatabase(WCDBOpenHelper.java:58)
        at android.arch.persistence.room.RoomDatabase.beginTransaction(RoomDatabase.java:252)

![image](https://user-images.githubusercontent.com/16219371/54524621-62f67680-49ad-11e9-81b5-b66f6be06b43.png)

you fix this crash in wcdb-android-1.0.3. I run same code on android api 23,its ok

**Comment by John-He-928** [comment]
Fixed in master branch

**Comment by weizhenguo321** [comment]
请问从哪个版本开始修复的？
