### ISSUE TITLE
android Q 崩溃问题

### ISSUE THREAD

**Issue by megahertz0** [Tencent/wcdb#485]
### The language of WCDB

>  Java 

### The version of WCDB

> 1.0.8

### The platform of WCDB

> Android Q

### The installation of WCDB

> Maven

### What's the issue?

E/AndroidRuntime: FATAL EXCEPTION: main
    com.tencent.wcdb.database.SQLiteException: failed to load ICU library. (code 1, errno -1): Database connection initializer failed.
        at com.tencent.wcdb.database.SQLiteConnection.nativeOpen(Native Method)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:254)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:238)
        at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:502)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:216)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
        at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:997)
        at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:978)
        at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
        at com.tencent.wcdb.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:852)

**Comment by John-He-928** [comment]
Fixed in master branch

**Comment by SanfenR** [comment]
我也遇到了这个问题，修改后的版本有更新么？

**Comment by wind24** [comment]
请问什么时候会release呢

**Comment by JoelJay** [comment]
Android Q在2019 Q3就会正式发版了，最近有fix这个问题的release计划吗？

**Comment by Jiaptti** [comment]
解决了吗？
