### ISSUE TITLE
打开数据库native crash

### ISSUE THREAD

**Issue by twlkyao** [Tencent/wcdb#554]
### The language of WCDB

>Java

### The version of WCDB

>v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

Native Crash
java堆栈：
```
at com.tencent.wcdb.database.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java:-2)

at com.tencent.wcdb.database.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:17104919)

at com.tencent.wcdb.database.SQLiteConnection.executeForString(SQLiteConnection.java:50659348)

at com.tencent.wcdb.database.SQLiteConnection.setJournalMode(SQLiteConnection.java:17104899)

at com.tencent.wcdb.database.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:196631)

at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:327733)

at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:100859915)

at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:33751053)

at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:131075)

at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:84082710)

at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:50593814)

at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:50593792)

at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:117768197)

at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:134610966)

at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:17170549)

at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:131074)
```
主堆栈
```
Operating system: Android
                  0.0.0 Linux 3.18.35+ #1 SMP PREEMPT Tue Jan 30 20:14:44 CST 2018 armv7l
CPU: arm
     ARMv7 ARM part(0x4100d030) features: half,thumb,fastmult,vfpv2,edsp,neon,vfpv3,tls,vfpv4,idiva,idivt
     8 CPUs

GPU: UNKNOWN

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x54
Process uptime: not available

Thread 0 (crashed)
 0  libwcdb.so + 0x4f62c
     r0 = 0x00000000    r1 = 0x8a4b8501    r2 = 0x8a87a428    r3 = 0x00000000
     r4 = 0xb1003008    r5 = 0x00000001    r6 = 0xa59526a8    r7 = 0x8aa7ad54
     r8 = 0x8aa7b040    r9 = 0x8bc39a5f   r10 = 0x00000000   r12 = 0x00000000
     fp = 0xa59526a8    sp = 0x8aa7ad18    lr = 0x00000000    pc = 0x8bbc162c
    Found by: given as instruction pointer in context
 1  libwcdb.so + 0x50901
     sp = 0x8aa7ad38    pc = 0x8bbc2903
    Found by: stack scanning
 2  libwcdb.so + 0xd9702
     sp = 0x8aa7ad44    pc = 0x8bc4b704
    Found by: stack scanning
 3  libwcdb.so + 0xcaff6
     sp = 0x8aa7ad48    pc = 0x8bc3cff8
    Found by: stack scanning
 4  libwcdb.so + 0x6aa35
     sp = 0x8aa7ad58    pc = 0x8bbdca37
    Found by: stack scanning
 5  libwcdb.so + 0xc7a5d
     sp = 0x8aa7ad7c    pc = 0x8bc39a5f
    Found by: stack scanning
 6  libwcdb.so + 0x71267
     sp = 0x8aa7ad88    pc = 0x8bbe3269
    Found by: stack scanning
 7  libwcdb.so + 0xc7a5d
     sp = 0x8aa7ada4    pc = 0x8bc39a5f
    Found by: stack scanning
 8  libwcdb.so + 0xcd4aa
     sp = 0x8aa7ada8    pc = 0x8bc3f4ac
    Found by: stack scanning
 9  libwcdb.so + 0xcd4ac
     sp = 0x8aa7adac    pc = 0x8bc3f4ae
    Found by: stack scanning
10  libwcdb.so + 0x2b83f
     sp = 0x8aa7adc8    pc = 0x8bb9d841
    Found by: stack scanning
11  libwcdb.so + 0x71491
     sp = 0x8aa7ae00    pc = 0x8bbe3493
    Found by: stack scanning
12  libwcdb.so + 0x714fd
     sp = 0x8aa7ae18    pc = 0x8bbe34ff
    Found by: stack scanning
13  libwcdb.so + 0x654bf
     sp = 0x8aa7ae20    pc = 0x8bbd74c1
    Found by: stack scanning
14  libart.so + 0x1e60f5
     sp = 0x8aa7ae30    pc = 0xb00780f7
    Found by: stack scanning
15  base.odex + 0x2007956
     sp = 0x8aa7ae40    pc = 0x96e6a958
    Found by: stack scanning
16  base.odex + 0x2007946
     sp = 0x8aa7ae44    pc = 0x96e6a948
    Found by: stack scanning
17  libwcdb.so + 0xcbc6b
     sp = 0x8aa7ae58    pc = 0x8bc3dc6d
    Found by: stack scanning
18  libart.so + 0xa94c1
     sp = 0x8aa7aea0    pc = 0xaff3b4c3
    Found by: stack scanning
19  boot.oat + 0x2bb7f3
     sp = 0x8aa7aeb8    pc = 0x71d107f5
    Found by: stack scanning
20  libwcdb.so + 0x691b5
     sp = 0x8aa7af20    pc = 0x8bbdb1b7
    Found by: stack scanning
21  libart.so + 0x98bfe
     sp = 0x8aa7af34    pc = 0xaff2ac00
    Found by: stack scanning
22  libart.so + 0x40340d
     sp = 0x8aa7af40    pc = 0xb029540f
    Found by: stack scanning
23  libart.so + 0xa949d
     sp = 0x8aa7af80    pc = 0xaff3b49f
    Found by: stack scanning
24  libwcdb.so + 0xd8c1a
     sp = 0x8aa7af9c    pc = 0x8bc4ac1c
    Found by: stack scanning
25  libwcdb.so + 0xd84aa
     sp = 0x8aa7afa0    pc = 0x8bc4a4ac
    Found by: stack scanning
26  libwcdb.so + 0xd8c1a
     sp = 0x8aa7afa4    pc = 0x8bc4ac1c
    Found by: stack scanning
27  libwcdb.so + 0xdb316
     sp = 0x8aa7afa8    pc = 0x8bc4d318
    Found by: stack scanning
28  libwcdb.so + 0xd8882
     sp = 0x8aa7afac    pc = 0x8bc4a884
    Found by: stack scanning
29  libart.so + 0x403fab
     sp = 0x8aa7afb0    pc = 0xb0295fad
    Found by: stack scanning
30  libwcdb.so + 0x3966f
     sp = 0x8aa7afd8    pc = 0x8bbab671
    Found by: stack scanning
31  libwcdb.so + 0x6a6fb
     sp = 0x8aa7b010    pc = 0x8bbdc6fd
    Found by: stack scanning
32  boot.oat + 0x312b5c
     sp = 0x8aa7b034    pc = 0x71d67b5e
    Found by: stack scanning

Loaded modules:
0x71a55000 - 0x722b0fff  boot.oat  ???  (main)  (WARNING: No symbols, boot.oat, F7063CB584C8D698B21422A077C0B4230)
0x8bb72000 - 0x8bc59fff  libwcdb.so  ???  (WARNING: No symbols, libwcdb.so, 2178444A40D957A6620C2A944011CC570)
0x94e63000 - 0x98006fff  base.odex  ???  (WARNING: No symbols, base.odex, C6A331EDB68853E177320BE51CC842180)
0xafe92000 - 0xb02f2fff  libart.so  ???  (WARNING: No symbols, libart.so, 9C2E7F411E194B029B020BCC8797CBF80)
```

**Comment by twlkyao** [comment]
请问有进展么

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
