### ISSUE TITLE
wcdb在Android 10必现crash

### ISSUE THREAD

**Issue by WinnieZy** [Tencent/wcdb#599]
### The language of WCDB
>  Java 

### The version of WCDB
> v1.0.8

### The platform of WCDB
>  Android

### The installation of WCDB
> AAR Package

### What's the issue?

wcdb在Android 10上必现crash，日志堆栈如下

2019-09-03 11:01:11.685 29866-29866/com.zy.wcdb.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zy.wcdb.demo, PID: 29866
    java.lang.RuntimeException: Unable to start activity ComponentInfocom.zy.wcdb.demo/com.zy.wcdb.demo.storage.db.cruddb.CRUDActivity}: com.tencent.wcdb.database.SQLiteException: Failed to register SQLite functions: not an error, ErrCode: 1 (code 1, errno -1): Database connection initializer failed.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3355)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3491)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7424)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)
     Caused by: com.tencent.wcdb.database.SQLiteException: Failed to register SQLite functions: not an error, ErrCode: 1 (code 1, errno -1): Database connection initializer failed.
        at com.tencent.wcdb.database.SQLiteConnection.nativeOpen(Native Method)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:254)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:238)
        at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:502)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:216)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
        at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:997)
        at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:978)
        at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
        at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:151)
        at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
        at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)
        at com.zy.wcdb.demo.storage.db.cruddb.PersonDBManager.<init>(PersonDBManager.java:22)
        at com.zy.wcdb.demo.storage.db.cruddb.CRUDActivity.onCreate(CRUDActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7736)
        at android.app.Activity.performCreate(Activity.java:7725)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3330)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3491) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7424) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938) 

机型图片如下：
![image](https://user-images.githubusercontent.com/15833215/64703394-e3baa900-d4de-11e9-9f9c-198857200438.png)

麻烦尽快帮忙看看是什么问题，谢谢！

**Comment by hyl87** [comment]
@RingoD

**Comment by John-He-928** [comment]
Master branch fixed this issue, but not released yet. Try building master branch.
