### ISSUE TITLE
全文搜索crash

### ISSUE THREAD

**Issue by chenfuxu920** [Tencent/wcdb#612]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Java

### The version of WCDB

> e.g. v1.0.5

1.0.8

### The platform of WCDB

> e.g. iOS, macOS or Android

Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

`     Caused by: com.tencent.wcdb.database.SQLiteException: malformed MATCH expression: [(] (code 1, errno 0): 
        at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at com.tencent.wcdb.database.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:935)
        at com.tencent.wcdb.database.SQLiteSession.executeForCursorWindow(SQLiteSession.java:791)
        at com.tencent.wcdb.database.SQLiteQuery.fillWindow(SQLiteQuery.java:63)
        at com.tencent.wcdb.database.SQLiteCursor.fillWindow(SQLiteCursor.java:146)
        at com.tencent.wcdb.database.SQLiteCursor.getCount(SQLiteCursor.java:135)`

分词器使用的是mmicu，搜索“(”这类特殊字符时会crash，需要使用转义符转义吗，我在网上没有找到有用信息，恳请解答，谢谢

**Comment by John-He-928** [comment]
Post your SQL statement.

FTS3/4 syntax is documented in [SQLite official site](https://www.sqlite.org/fts3.html). The syntax applies to all FTS3/4 queries, regardless of which tokenizer to use.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
