### ISSUE TITLE
SQLiteGlobal.nativeSetDefaultPageSize 内部报signal 11 (SIGSEGV)错误

### ISSUE THREAD

**Issue by weizhenguo321** [Tencent/wcdb#659]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

Native堆栈：
pid: 0, tid: 18187, name: Thread-1448  >>> (null) <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xd467722f
    r0  d467722f  r1  00001000  r2  00001000  r3  64df8cc0
    r4  00001000  r5  1da00001  r6  00000000  r7  00000000
    r8  00001000  r9  00000000  sl  00000000  fp  00000000
    ip  00000000  sp  749a8f00  lr  155331cd  pc  15533014  cpsr  00000000

backtrace:
    #00 pc 00033014  /data/app-lib/.../libwcdb.so (sqlcipher_codec_ctx_get_kdf_iter+208907)
    #01 pc 000331cb  /data/app-lib/.../libwcdb.so (sqlcipher_get_default_pagesize+209353)

Java堆栈：
  at com.tencent.wcdb.database.SQLiteGlobal.nativeSetDefaultPageSize(SourceFile:-2)
  at com.tencent.wcdb.database.SQLiteGlobal.<clinit>(SourceFile:262175)
  at com.tencent.wcdb.database.j.<clinit>(SourceFile:0)
  ...
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:841)

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
