### ISSUE TITLE
使用 BackupKit工具进行数据库备份，出现JNI崩溃；导致app无法使用

### ISSUE THREAD

**Issue by geolo123** [Tencent/wcdb#695]
### The language of WCDB
android/java

### The version of WCDB
v1.0.8

### The platform of WCDB
 Android

### The installation of WCDB
maven

### What's the issue?

> Post the outputs or screenshots for errors.

2020-03-28 16:51:13.574 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xb1
2020-03-28 16:51:13.574 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]     string: '��8K
2020-03-28 16:51:13.574 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��$	��7���3����7'�3��$
2020-03-28 16:51:13.574 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] ��7�*�3����79�3����7�3����7>#�3����7�*�3����7�*�3����7�+�3����7�2�3����7�2�3����7	}�3��8?
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8@
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8A
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8B
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8C
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8D
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8E
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8F
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8G
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8H
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8I
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8J
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8R
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3����7s��3����7�+�3��
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] ��7�2�3����7V��3����7���3����7���3��8L
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8M
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8N
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8O
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8P
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8Q
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��:fr�3��8h
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8i
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8g
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��:ir�3��8n
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8o
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8m
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��:kr�3��8k
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8l
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8j
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��:jr�3��8Z
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��$	��7�B�3��$	��7�H�3��$	��7ȑ�3��8W
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8X
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8Y
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�7n77B[7��3��8\
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8_
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�7n77K[7��3��8_
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8`
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8^
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8b
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8b
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8c
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8a
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8e
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8h
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8k
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8n
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8q
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8q
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8r
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8p
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8t
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8w
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8w
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8x
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8v
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8z
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8z
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8{
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8y
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8}
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8}
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8~
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8|
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c77�[7��3��8
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��$	��7�H�3����7�H�3����7�H�3����7�H�3��$	��7�|�3����7�|�3����7!��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7)m77�[7��3��7�i77�i7��3��7n77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c7Il77�[7��3��7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�c77�[7��3��7n77�[7��3��7�7[l77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] ��7A2�3��8��3��7&7.c7�7il�3��7'i77"c7�c79�3��7�3��7�3��77il7��3��7�3��77il7��3����7���3��7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�c77�[7��3��:�t�3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��$	��7	D�3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] 8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7il7�c77�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�c77�[7��3��8+�3��8,�3��8*�3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��7�c77�[7��3��7*o77Yl7�[7��3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��8�
2020-03-28 16:51:13.575 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] �3��'
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]     input: '<0xb1> 0xe2 0x05 0x38 0x4b 0x0a 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x24 0x09 0x04 0xc7 0xdd 0x04 0x37 0xb8 0x87 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0x27 0x15 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x24 0x0a 0x06 0xc7 0xdd 0x04 0x37 0xb7 0x2a 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0x39 0x17 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0x7f 0x17 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x1a 0xc7 0xdd 0x04 0x37 0x3e 0x23 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0xb6 0x2a 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0xb8 0x2a 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0x85 0x2b 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0xa4 0x32 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0xa5 0x32 0x02 0xae 0x33 0x02 0xc4 0xf4 0x02 0x04 0x19 0xc7 0xdd 0x04 0x37 0x09 0x7d 0x02 0xaf 0x33 0x01 0xb1 0xe2 0x05 0x
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]     in call to NewStringUTF
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]     from java.lang.String com.tencent.wcdb.repair.BackupKit.nativeLastError(long)
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470] "main" prio=5 tid=1 Runnable
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x77edfb18 self=0x7f976a2a00
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   | sysTid=30673 nice=0 cgrp=default sched=0/0 handle=0x7f9b756a98
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 2948994950 44636606 770 ) utm=281 stm=13 core=1 HZ=100
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   | stack=0x7fcae22000-0x7fcae24000 stackSize=8MB
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   at com.tencent.wcdb.repair.BackupKit.nativeLastError(Native method)
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   at com.tencent.wcdb.repair.BackupKit.run(BackupKit.java:150)
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   at com.sankuai.sjst.syncpo.shop.android.base.db.sqlite.TradeDatabaseHelper.onBackupTradeDb(TradeDatabaseHelper.java:180)
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   at com.sankuai.sjst.syncpo.shop.android.base.db.sqlite.TradeDatabaseHelper.<init>(TradeDatabaseHelper.java:79)
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   at com.sankuai.sjst.syncpo.shop.android.base.db.sqlite.TradeDatabaseHelper.getHelper(TradeDatabaseHelper.java:105)
2020-03-28 16:51:13.576 30673-30673/com.syncpo.client.shop.android A/art: art/runtime/java_vm_ext.cc:470]   - locked <0x0f093c89> (a java.lang.Object)

> 
> Explain what you want by example or code **in English**.

`private static void onBackupTradeDb(SQLiteDatabase db) {
      
        try {
            long startTime = System.currentTimeMillis();
        
            backupDatabaseKit = new BackupKit(
                    // 要备份的 DB
                    db,
                    // 备份文件
                    db.getPath() + "-backup",
                    // 加密备份文件的密钥，非 DB 密钥
                    null,
                    0, null);

            int result = backupDatabaseKit.run();
            switch (result) {
                default:
                    break;
                /* 成功 */
                case BackupKit.RESULT_OK:
                
                    break;
                /* 取消操作 */
                case BackupKit.RESULT_CANCELED:
                    
                    break;
                /* 失败 */
                case BackupKit.RESULT_FAILED:
                   
                    break;
            }
            String errorInfo = backupDatabaseKit.lastError();
            logger.info("数据库的备份的错误信息; errorInfo:{}", errorInfo);
            backupDatabaseKit.release();
            logger.info("结束执行数据库的备份,耗时:{}ms", (System.currentTimeMillis() - startTime));
        } catch (Exception e) {
            logger.error("执行数据库的备份异常", e);
        }`

**Comment by geolo123** [comment]
![image](https://user-images.githubusercontent.com/7976884/77819325-088e0b00-7115-11ea-939b-1687c64b1419.png)

**Comment by geolo123** [comment]
![image](https://user-images.githubusercontent.com/7976884/77819345-278c9d00-7115-11ea-9171-0db73886a146.png)

**Comment by geolo123** [comment]
找到问题了；
 armeabi-v7a  is ok ，可以成功；
v8a is fail；会奔溃；

请问大佬们，可以修复v8a的问题吗？  cpu类型，cpu abi type

**Comment by geolo123** [comment]
找到问题了；
 armeabi-v7a  is ok ，可以成功；
v8a is fail；会奔溃；

请问大佬们，可以修复v8a的问题吗？  cpu类型，cpu abi type

**Comment by haizhiyun** [comment]
> 找到问题了；
> armeabi-v7a is ok ，可以成功；
> v8a is fail；会奔溃；
> 
> 请问大佬们，可以修复v8a的问题吗？ cpu类型，cpu abi type

这个问题修复了没，感觉这个库没有人维护了

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0. Data backup and recovery capabilities have been significantly improved.
