### ISSUE TITLE
插入数据崩溃

### ISSUE THREAD

**Issue by LeaYw** [Tencent/wcdb#749]
### The language of WCDB

> Java 

### The version of WCDB

> e.g. v2.4.0

### The platform of WCDB

> Android

### The installation of WCDB

>Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

E/TestRunner: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.HashMap.keySet()' on a null object reference
        at com.tencent.wcdb.database.SQLiteDatabase.keySet(SQLiteDatabase.java:1622)
        at com.tencent.wcdb.database.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1662)
        at com.tencent.wcdb.database.SQLiteDatabase.insert(SQLiteDatabase.java:1530)

**Comment by JipingWei** [comment]
同样崩溃，有解法么

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.
