### ISSUE TITLE
Android 11 模拟器 崩溃

### ISSUE THREAD

**Issue by chenguozhi** [Tencent/wcdb#750]
### The language of WCDB

> Java 

### The version of WCDB

> e.g. v1.0.8

### The platform of WCDB

> e.g. Android

### The installation of WCDB

> e.g.  Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

2020-08-12 10:19:48.455 8792-8792/? E/EChatApp: Unable to start activity ComponentInfo{com.ruaho.cochat.cn.debug/com.ruaho.cochat.setting.activity.SplashActivity}: com.tencent.wcdb.database.SQLiteException: failed to load ICU library. (code 1, errno -1): Database connection initializer failed.
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ruaho.cochat.cn.debug/com.ruaho.cochat.setting.activity.SplashActivity}: com.tencent.wcdb.database.SQLiteException: failed to load ICU library. (code 1, errno -1): Database connection initializer failed.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.tencent.wcdb.database.SQLiteException: failed to load ICU library. (code 1, errno -1): Database connection initializer failed.
        at com.tencent.wcdb.database.SQLiteConnection.nativeOpen(Native Method)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:254)
        at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:238)
        at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:502)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:216)
        at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
        at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:997)
        at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:978)
        at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
        at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:151)
        at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
        at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)

**Comment by chenguozhi** [comment]
com.tencent.wcdb.database.SQLiteException: failed to load ICU library. (code 1, errno -1): Database connection initializer failed.
