### ISSUE TITLE
com.tencent.wcdb.database.SQLiteException: unknown database: old (code 1, errno 0): Cannot checkpoint the WAL database

### ISSUE THREAD

**Issue by 308129331** [Tencent/wcdb#937]
### The language of WCDB

-> java or kotlin

### The version of WCDB

> v1.0.8

### The platform of WCDB

>Android

### The installation of WCDB

>com.tencent.wcdb:wcdb-android:1.0.8

### What's the issue?

> 
Thread Name: 'WCDB.AsyncCheckpointer'

Back traces starts.

com.tencent.wcdb.database.SQLiteException: unknown database: old (code 1, errno 0): Cannot checkpoint the WAL database

	at com.tencent.wcdb.database.SQLiteConnection.nativeWalCheckpoint(SQLiteConnection.java)

	at com.tencent.wcdb.database.SQLiteConnection.walCheckpoint(SQLiteConnection.java:976)

	at com.tencent.wcdb.database.SQLiteSession.walCheckpoint(SQLiteSession.java:802)

	at com.tencent.wcdb.database.SQLiteDatabase.walCheckpoint(SQLiteDatabase.java:1925)

	at com.tencent.wcdb.database.SQLiteAsyncCheckpointer.handleMessage(SQLiteAsyncCheckpointer.java:118)

	at android.os.Handler.dispatchMessage(Handler.java:102)

	at android.os.Looper.loop(Looper.java:201)

	at android.os.HandlerThread.run(HandlerThread.java:65)

Back traces ends.
> 
> Mostly happening in Android 9，not work well。

**Comment by Qiuwen-chen** [comment]
We will handle it in the developing WCDB Java.
